# Pandas 


## AI의 데이터는 DB가 아님 --> DataFrame
- 데이터 프레임 df 
- Jupyter 가 권장됨 VS code X

- Pandas는 파이썬에서 데이터를 분석하고 처리하는데 가장 많이 사용하고 강력한 라이브러리
- 엑셀처럼 테이블 형식의 표 데이터를 핸들링이 가능하며 이 개념을 우리는 데이터 프레임(DataFrame) 구조라고 정의

- 데이터 등을 수집해서 정리 , 가공 , 데이터 분석 , 데이터 인사이트 도출
- 이때 , 주피터노트북이 이 과정에서 가장 좋은 도구로 평가 받고 있음
  
- 정형 : csv,excel,database
- 반정형 (semi-structured ) : xml , json   
- 비정형 : 이미지 , 동영상 , 음성 , 홍채 인식 등등
    
    - 결론적으로 , 테이블 형식의 구조화된 데이터를 핸들하고 분석할때 최적화된 도구이자 라이브러리
    - DF = 시그마 Series
    -

In [2]:
import pandas as pd

In [4]:
x = pd.Series([7,3,5,8],index = ['서울','천안','아산','평택'])
x

서울    7
천안    3
아산    5
평택    8
dtype: int64

In [5]:
print(x['서울'])

7

In [13]:
가져올목록 = ['서울','천안']
print(x[가져올목록])

서울    7
천안    3
dtype: int64

In [11]:
print(x[['서울','천안']]) # 데이터 프레임으로 호출

서울    7
천안    3
dtype: int64

In [14]:
x.index

Index(['서울', '천안', '아산', '평택'], dtype='object')

In [18]:
sorted(x.index)

['서울', '아산', '천안', '평택']

In [20]:
x.values

array([7, 3, 5, 8])

In [22]:
a = [1,3,2,4,2,3]
x = pd.Series(a)
x

0    1
1    3
2    2
3    4
4    2
5    3
dtype: int64

In [23]:
pd.unique(x) # 중복 제거

array([1, 3, 2, 4])

In [24]:
data = {
    '이름' : ['강동균','김영곤','김현수','노경환'],
    '학점' : [90,83,93,88],
    '학년' : [4,3,4,3]}

In [28]:
df = pd.DataFrame(data)
df

    이름  학점  학년
0  강동균  90   4
1  김영곤  83   3
2  김현수  93   4
3  노경환  88   3

In [33]:
df.to_csv('students.csv', index = False ,encoding = 'utf-8')

# utf-8(-sig)
# EUC-KR
# cp949
# 환경에 따라 다르기 때문에 세가지 전부 시도 해봐야함

In [4]:
df2 = pd.read_csv('students.csv', encoding = 'utf-8' , index_col = 0) # 불러올때 인덱스 무시 
df2

     학점  학년
이름
강동균  90   4
김영곤  83   3
김현수  93   4
노경환  88   3

In [7]:
data = {'age':[22,23,24,25,28,30,21,26,27,20],
        'name':['동균','영곤','현수','경환','준환','지민','창석','경현','영준','순나'],
        'height':[186,185,175,178,190,165,169,160,177,172]}
data

{'age': [22, 23, 24, 25, 28, 30, 21, 26, 27, 20],
 'name': ['동균', '영곤', '현수', '경환', '준환', '지민', '창석', '경현', '영준', '순나'],
 'height': [186, 185, 175, 178, 190, 165, 169, 160, 177, 172]}

In [8]:
df = pd.DataFrame(data)
df

   age name  height
0   22   동균     186
1   23   영곤     185
2   24   현수     175
3   25   경환     178
4   28   준환     190
5   30   지민     165
6   21   창석     169
7   26   경현     160
8   27   영준     177
9   20   순나     172

In [10]:
df = pd.DataFrame(data,columns = ['name','age','height']) # shift + Tab : 함수 보기 
df

  name  age  height
0   동균   22     186
1   영곤   23     185
2   현수   24     175
3   경환   25     178
4   준환   28     190
5   지민   30     165
6   창석   21     169
7   경현   26     160
8   영준   27     177
9   순나   20     172

In [12]:
df['name']

0    동균
1    영곤
2    현수
3    경환
4    준환
5    지민
6    창석
7    경현
8    영준
9    순나
Name: name, dtype: object

In [13]:
df.head() # 상위 n개 행( 기본 5개 ) 확인

  name  age  height
0   동균   22     186
1   영곤   23     185
2   현수   24     175
3   경환   25     178
4   준환   28     190

In [14]:
df.tail() # df의 마지막 n개 행 (기본 5개)

  name  age  height
5   지민   30     165
6   창석   21     169
7   경현   26     160
8   영준   27     177
9   순나   20     172

In [15]:
df.shape

(10, 3)

In [16]:
df.columns

Index(['name', 'age', 'height'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   age     10 non-null     int64
 2   height  10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

non - null 결측치는 제거가 아닌 처리의 대상이다

column = input 변수 

찾고자 하는 값 target = output

In [18]:
df.describe()   # 수학적 기술통계

             age      height
count  10.000000   10.000000
mean   24.600000  175.700000
std     3.204164    9.569047
min    20.000000  160.000000
25%    22.250000  169.750000
50%    24.500000  176.000000
75%    26.750000  183.250000
max    30.000000  190.000000

In [19]:
df[['name','age']]

  name  age
0   동균   22
1   영곤   23
2   현수   24
3   경환   25
4   준환   28
5   지민   30
6   창석   21
7   경현   26
8   영준   27
9   순나   20

In [20]:
df.iloc[0]   # 인덱스위치의 값

name       동균
age        22
height    186
Name: 0, dtype: object

In [21]:
df.loc[1,'name']  # 인덱스 번호 와 컬럼명 에 맞는 값 도출

'영곤'

In [22]:
data = [[1,2],[3,4],[5,6]]
df = pd.DataFrame(data, columns = ['First','Second'])
df

   First  Second
0      1       2
1      3       4
2      5       6

In [23]:
df.iloc[1]

First     3
Second    4
Name: 1, dtype: int64

In [24]:
df.iloc[:,-1]

0    2
1    4
2    6
Name: Second, dtype: int64

In [26]:
df.iloc[:-2]

   First  Second
0      1       2

[데이터 프레임 연습]

In [51]:
df = pd.DataFrame({
    "이름": ["철수", "영희", "민수", "지영"],
    "나이": [25, 30, 28, 35],
    "부서": ["영업", "개발", "개발", "인사"],
    "연봉": [3500, 5000, 4800, 4200],
})
df

   이름  나이  부서    연봉
0  철수  25  영업  3500
1  영희  30  개발  5000
2  민수  28  개발  4800
3  지영  35  인사  4200

In [28]:
df.describe()

              나이           연봉
count   4.000000     4.000000
mean   29.500000  4375.000000
std     4.203173   675.154303
min    25.000000  3500.000000
25%    27.250000  4025.000000
50%    29.000000  4500.000000
75%    31.250000  4850.000000
max    35.000000  5000.000000

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      object
 1   나이      4 non-null      int64
 2   부서      4 non-null      object
 3   연봉      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [31]:
df.loc[1,"이름"]

'영희'

In [32]:
df.iloc[0:2]

   이름  나이  부서    연봉
0  철수  25  영업  3500
1  영희  30  개발  5000

In [33]:
df.loc[:,["이름","부서"]]

   이름  부서
0  철수  영업
1  영희  개발
2  민수  개발
3  지영  인사

In [35]:
df.head()

   이름  나이  부서    연봉
0  철수  25  영업  3500
1  영희  30  개발  5000
2  민수  28  개발  4800
3  지영  35  인사  4200

In [52]:
df["연봉_원"] = df["연봉"] * 10000 # 파생변수 
# 머신러닝에서는 new feature 

df

   이름  나이  부서    연봉      연봉_원
0  철수  25  영업  3500  35000000
1  영희  30  개발  5000  50000000
2  민수  28  개발  4800  48000000
3  지영  35  인사  4200  42000000

In [43]:
df = df.rename(columns = {"연봉" : "연봉_만원"}) 
df

   이름  나이  부서  연봉_만원      연봉_원
0  철수  25  영업   3500  35000000
1  영희  30  개발   5000  50000000
2  민수  28  개발   4800  48000000
3  지영  35  인사   4200  42000000

In [54]:
df.drop(columns = ["연봉_원"],inplace = True) # inplace True : 바로 갱신 , 필드에서 자주 씀 
df

KeyError: "['연봉_원'] not found in axis"

In [45]:
df

   이름  나이  부서  연봉_만원      연봉_원
0  철수  25  영업   3500  35000000
1  영희  30  개발   5000  50000000
2  민수  28  개발   4800  48000000
3  지영  35  인사   4200  42000000

In [46]:
df2 = df.drop(columns = ["연봉_원"])
df2

   이름  나이  부서  연봉_만원
0  철수  25  영업   3500
1  영희  30  개발   5000
2  민수  28  개발   4800
3  지영  35  인사   4200