In [17]:
import pandas as pd
import numpy as np

In [31]:
data = {'학번': range(2000, 2010),
       '전공성적1' : [85, 95, 75, np.nan , 100, 100, 95, 85, 80, 85], 
       '전공성적2' : [95, 95, 100, 80, 100, 100, 95, 85, np.nan, 85],
       '전공성적3' : [np.nan, np.nan, np.nan, np.nan, 100, np.nan, 95, 85, np.nan, 85]}

In [58]:
df = pd.DataFrame(data)
df

Empty DataFrame
Columns: []
Index: []

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학번      10 non-null     int64
 1   전공성적1   9 non-null      float64
 2   전공성적2   9 non-null      float64
 3   전공성적3   4 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 452.0 bytes

In [22]:
df.isnull()

      학번  전공성적1  전공성적2  전공성적3
0  False  False  False   True
1  False  False  False   True
2  False  False  False   True
3  False   True  False   True
4  False  False  False  False
5  False  False  False   True
6  False  False  False  False
7  False  False  False  False
8  False  False   True   True
9  False  False  False  False

In [23]:
df.isnull().sum() # 결측 합계

학번       0
전공성적1    1
전공성적2    1
전공성적3    6
dtype: int64

In [25]:
df.dropna(inplace=True)
df

     학번  전공성적1  전공성적2  전공성적3
4  2004  100.0  100.0  100.0
6  2006   95.0   95.0   95.0
7  2007   85.0   85.0   85.0
9  2009   85.0   85.0   85.0

In [34]:
df.fillna(0,inplace=True)     # 결측치 보충 ( 최소 , 평균 , 최대 , 0 )
df                         # 현장과 데이터 특성에 따라 판단

     학번  전공성적1  전공성적2  전공성적3
0  2000   85.0   95.0    0.0
1  2001   95.0   95.0    0.0
2  2002   75.0  100.0    0.0
3  2003    0.0   80.0    0.0
4  2004  100.0  100.0  100.0
5  2005  100.0  100.0    0.0
6  2006   95.0   95.0   95.0
7  2007   85.0   85.0   85.0
8  2008   80.0    0.0    0.0
9  2009   85.0   85.0   85.0

In [43]:
# ===== 실습용 가상 '직원 데이터' 생성 함수 =====
# 실제처럼 패턴이 있는 데이터: 경력↑·교육수준↑ → 연봉↑, 부서별 차이 존재
def employee(n=200, seed=42):
    rng = np.random.default_rng(seed)                  # 재현 가능한 난수 생성기
    부서 = rng.choice(["영업", "개발", "인사", "마케팅"], n, p=[0.35, 0.35, 0.10, 0.20])
    교육 = rng.choice(["고졸", "대졸", "석사", "박사"], n, p=[0.20, 0.50, 0.25, 0.05])
    경력 = rng.integers(0, 21, n)                       # 0~20년
    나이 = (24 + 경력 + rng.integers(-2, 3, n)).astype(int)
    # 연봉(만원): 기본 + 경력 + 교육보너스 + 부서보너스 + 약간의 무작위
    교육보너스 = pd.Series(교육).map({"고졸": 0, "대졸": 300, "석사": 700, "박사": 1200}).values
    부서보너스 = pd.Series(부서).map({"영업": 200, "개발": 500, "인사": 0, "마케팅": 150}).values
    연봉 = 3000 + 경력 * 150 + 교육보너스 + 부서보너스 + rng.normal(0, 300, n)
    df = pd.DataFrame({
        "사번": range(1001, 1001 + n),
        "부서": 부서,
        "교육수준": 교육,
        "나이": 나이,
        "경력": 경력,
        "연봉": 연봉.round(0).astype(int),
    })
    return df

In [59]:
df2 = employee(100).copy()
df2

      사번   부서 교육수준  나이  경력    연봉
0   1001   인사   석사  42  20  6612
1   1002   개발   대졸  41  16  6169
2   1003  마케팅   대졸  32   6  4274
3   1004   개발   박사  46  20  7746
4   1005   영업   석사  33  10  5841
..   ...  ...  ...  ..  ..   ...
95  1096   개발   고졸  34   8  4325
96  1097   개발   대졸  26   2  3620
97  1098   영업   석사  32   7  4712
98  1099   영업   고졸  44  19  6182
99  1100  마케팅   대졸  33   8  4807

[100 rows x 6 columns]

In [60]:
df2.loc[2:5,"연봉"] = np.nan
df2.loc[7,"교육수준"] = np.nan
df2

      사번   부서 교육수준  나이  경력      연봉
0   1001   인사   석사  42  20  6612.0
1   1002   개발   대졸  41  16  6169.0
2   1003  마케팅   대졸  32   6     NaN
3   1004   개발   박사  46  20     NaN
4   1005   영업   석사  33  10     NaN
..   ...  ...  ...  ..  ..     ...
95  1096   개발   고졸  34   8  4325.0
96  1097   개발   대졸  26   2  3620.0
97  1098   영업   석사  32   7  4712.0
98  1099   영업   고졸  44  19  6182.0
99  1100  마케팅   대졸  33   8  4807.0

[100 rows x 6 columns]

In [48]:
df2.isnull().sum()

사번      0
부서      0
교육수준    1
나이      0
경력      0
연봉      4
dtype: int64

In [61]:
df2["연봉"] = df2["연봉"].fillna(df2["연봉"].mean())
df2

      사번   부서 교육수준  나이  경력           연봉
0   1001   인사   석사  42  20  6612.000000
1   1002   개발   대졸  41  16  6169.000000
2   1003  마케팅   대졸  32   6  5208.458333
3   1004   개발   박사  46  20  5208.458333
4   1005   영업   석사  33  10  5208.458333
..   ...  ...  ...  ..  ..          ...
95  1096   개발   고졸  34   8  4325.000000
96  1097   개발   대졸  26   2  3620.000000
97  1098   영업   석사  32   7  4712.000000
98  1099   영업   고졸  44  19  6182.000000
99  1100  마케팅   대졸  33   8  4807.000000

[100 rows x 6 columns]

In [62]:
df2.duplicated().sum()

np.int64(0)

In [63]:
# drop_duplicated()

## 이상치

- Q1 1사분위수 25%
- Q2 2사분위수(중간) 50%
- Q3 3사분위수 75%
- Q4 4사분위수(최대) 100%

이 범위 밖을 이상치 (이상값), outlier 
초극단치값을 포함한다. 

이상치는 제거의 대상이 아니라 관찰의 대상 !! ( 민감하게 봐야 함 )

### IQR - 이상치 처리 : Q3 - Q1 ( 3사분위 - 1사분위 )

- 정상범위: Q1 - 1.5 * IQR , Q3 + 1.5 * IQR
- 정상범위 외의 값을 Outlier 로 판단

In [65]:
Q1 = df2["연봉"].quantile(0.25)
Q3 = df2["연봉"].quantile(0.75)

IQR = Q3 - Q1

Lower = Q1 - 1.5 * IQR
Upper = Q3 + 1.5 * IQR

In [67]:
print("Q1 :",Q1)
print("Q3 :",Q3)
print("IQR :",IQR)
print("하한값 Lower:",Lower)
print("상한값 Upper:",Upper)
print("연봉 정상 범위 : " , Lower , "-" ,Upper)

Q1 : 4346.0
Q3 : 6136.0
IQR : 1790.0
하한값 Lower: 1661.0
상한값 Upper: 8821.0
연봉 정상 범위 :  1661.0 - 8821.0