In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/CARD_SUBWAY_MONTH_202102.csv',index_col = False)   # 상대 경로로 임포트
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20210201  중앙선   용문    1282    1259  20210204
1  20210201  중앙선   지평      48      43  20210204
2  20210201  중앙선   아신     415     413  20210204
3  20210201  중앙선   양수    1463    1466  20210204
4  20210201  중앙선  운길산     495     463  20210204

현장 문제 상황 
- unnamed 
- 컬럼 밀림

정합성 튜링 먼저 하고 분석

In [3]:
df.head(20)

        사용일자  노선명           역명  승차총승객수  하차총승객수      등록일자
0   20210201  중앙선           용문    1282    1259  20210204
1   20210201  중앙선           지평      48      43  20210204
2   20210201  중앙선           아신     415     413  20210204
3   20210201  중앙선           양수    1463    1466  20210204
4   20210201  중앙선          운길산     495     463  20210204
5   20210201  중앙선           팔당     687     662  20210204
6   20210201  중앙선           도심    2237    1736  20210204
7   20210201  중앙선           덕소    5139    5082  20210204
8   20210201  중앙선           양정     721     606  20210204
9   20210201  중앙선           도농    9067    8349  20210204
10  20210201  중앙선           구리   12403   12591  20210204
11  20210201  중앙선           양원    1451    1484  20210204
12  20210201  중앙선           망우    6789    6608  20210204
13  20210201  중앙선  상봉(시외버스터미널)    5141    5291  20210204
14  20210201  중앙선           중랑    4988    4730  20210204
15  20210201  중앙선           회기   20536   20077  20210204
16  20210201  장항선     신창(순천향대)     808     874  20210204
17  20210201  장항선         온양온천    2930    2893  20210204
18  20210201  장항선           배방     782     756  20210204
19  20210201  장항선           아산    2234    2017  20210204

EDA(탐색적 데이터 분석 : Exploratory Data Analysis)

- 데이터 셋을 변수들을 확인 
- 데이터의 전체적인 모습을 확인
    - 데이터 프레임의 형태 , 결측치 , 이상치 등 데이터 전반에 대한 분석
- 각 변수들의 전체적인 분포 현황을 확인 및 분석
- 변수들간의 경향성을 확인/분석
- 데이터의 시각적 분석 기법을 적용해서 데이터의 인사이트를 도출
- 머신러닝 모델을 사용해서 데이터 인사이트를 발굴하는데 사용이 가능
- 요인 , 변수 , x값 , input , 독립변수 , feature  => 상관관계 분석 및 도출

In [4]:
df.shape

(16751, 6)

In [5]:
df.columns

Index(['사용일자', '노선명', '역명', '승차총승객수', '하차총승객수', '등록일자'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16751 entries, 0 to 16750
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    16751 non-null  int64
 1   노선명     16751 non-null  object
 2   역명      16751 non-null  object
 3   승차총승객수  16751 non-null  int64
 4   하차총승객수  16751 non-null  int64
 5   등록일자    16751 non-null  int64
dtypes: int64(4), object(2)
memory usage: 785.3+ KB

In [7]:
df.describe()

               사용일자        승차총승객수        하차총승객수          등록일자
count  1.675100e+04  16751.000000  16751.000000  1.675100e+04
mean   2.021021e+07   8567.344696   8536.474419  2.021023e+07
std    8.083073e+00   9006.651687   9064.054078  2.749315e+01
min    2.021020e+07      1.000000      0.000000  2.021020e+07
25%    2.021021e+07   2652.500000   2594.500000  2.021021e+07
50%    2.021022e+07   5857.000000   5733.000000  2.021022e+07
75%    2.021022e+07  11257.000000  11117.000000  2.021022e+07
max    2.021023e+07  88904.000000  87891.000000  2.021030e+07

In [8]:
df.isnull().sum()

사용일자      0
노선명       0
역명        0
승차총승객수    0
하차총승객수    0
등록일자      0
dtype: int64

1. '노선' 컬럼이 가지고 있는 데이터의 종류 ?
    = 노선 데이터 분석

In [9]:
df["노선명"].unique()

array(['중앙선', '장항선', '일산선', '우이신설선', '안산선', '수인선', '분당선', '과천선',
       '공항철도 1호선', '경춘선', '경인선', '경의선', '경원선', '경부선', '경강선', '9호선2~3단계',
       '9호선', '8호선', '7호선', '6호선', '5호선', '4호선', '3호선', '2호선', '1호선'],
      dtype=object)

In [10]:
df["노선명"].nunique()   # 중복을 제거한 행 개수

25

In [11]:
print(f"현재 {df["노선명"].unique()}이 운행중이며 {df["노선명"].nunique()}개의 노선이 존재한다.")

현재 ['중앙선' '장항선' '일산선' '우이신설선' '안산선' '수인선' '분당선' '과천선' '공항철도 1호선' '경춘선' '경인선'
 '경의선' '경원선' '경부선' '경강선' '9호선2~3단계' '9호선' '8호선' '7호선' '6호선' '5호선' '4호선'
 '3호선' '2호선' '1호선']이 운행중이며 25개의 노선이 존재한다.

In [12]:
df["노선명"].value_counts()

노선명
5호선         1484
7호선         1428
2호선         1400
경부선         1092
6호선         1051
분당선          967
3호선          937
경원선          821
경의선          737
4호선          728
9호선          700
중앙선          588
경인선          560
경춘선          532
수인선          504
8호선          476
공항철도 1호선     392
9호선2~3단계     364
안산선          364
우이신설선        364
경강선          308
일산선          282
1호선          280
과천선          224
장항선          168
Name: count, dtype: int64

가장 많은 노선을 가지고 있는 5호선(1484건)이다.

In [13]:
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20210201  중앙선   용문    1282    1259  20210204
1  20210201  중앙선   지평      48      43  20210204
2  20210201  중앙선   아신     415     413  20210204
3  20210201  중앙선   양수    1463    1466  20210204
4  20210201  중앙선  운길산     495     463  20210204

2. 승하차 승객이 어떻게 변하는지 ? = 승하차객수에 대한 분석

In [14]:
df.sort_values(by = ["승차총승객수"])

           사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
13752  20210224  3호선  충무로       1       0  20210227
7584   20210213  경원선   창동       1       0  20210216
12626  20210222  3호선  충무로       1       0  20210225
12932  20210222  경원선   창동       1       0  20210225
13043  20210222  분당선   복정       1       0  20210225
...         ...  ...  ...     ...     ...       ...
14384  20210225  2호선   강남   84374   82960  20210228
14314  20210224  2호선   강남   84628   82667  20210227
13705  20210223  2호선   강남   84922   83364  20210226
10857  20210219  2호선   강남   86800   80948  20210222
14984  20210226  2호선   강남   88904   87891  20210301

[16751 rows x 6 columns]

In [15]:
# 내림차순으로 분석 
df.sort_values(by = ["승차총승객수"],ascending = False) # 오름차순 False

           사용일자  노선명    역명  승차총승객수  하차총승객수      등록일자
14984  20210226  2호선    강남   88904   87891  20210301
10857  20210219  2호선    강남   86800   80948  20210222
13705  20210223  2호선    강남   84922   83364  20210226
14314  20210224  2호선    강남   84628   82667  20210227
14384  20210225  2호선    강남   84374   82960  20210228
...         ...  ...   ...     ...     ...       ...
14346  20210224  일산선    지축       1       0  20210227
4853   20210209  분당선    복정       1       0  20210212
14425  20210225  3호선   충무로       1       0  20210228
10025  20210217  경의선  김포공항       1       0  20210220
13752  20210224  3호선   충무로       1       0  20210227

[16751 rows x 6 columns]

index 기준으로 데이터 정렬 분석

In [16]:
df.sort_index(ascending=False)

           사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
16750  20210228  중앙선   지평      30      31  20210303
16749  20210228  중앙선   용문    1899    1716  20210303
16748  20210228  중앙선   원덕     322     304  20210303
16747  20210228  중앙선   양평    3299    3187  20210303
16746  20210228  중앙선   오빈     216     236  20210303
...         ...  ...  ...     ...     ...       ...
4      20210201  중앙선  운길산     495     463  20210204
3      20210201  중앙선   양수    1463    1466  20210204
2      20210201  중앙선   아신     415     413  20210204
1      20210201  중앙선   지평      48      43  20210204
0      20210201  중앙선   용문    1282    1259  20210204

[16751 rows x 6 columns]

In [17]:
df[0:10]

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20210201  중앙선   용문    1282    1259  20210204
1  20210201  중앙선   지평      48      43  20210204
2  20210201  중앙선   아신     415     413  20210204
3  20210201  중앙선   양수    1463    1466  20210204
4  20210201  중앙선  운길산     495     463  20210204
5  20210201  중앙선   팔당     687     662  20210204
6  20210201  중앙선   도심    2237    1736  20210204
7  20210201  중앙선   덕소    5139    5082  20210204
8  20210201  중앙선   양정     721     606  20210204
9  20210201  중앙선   도농    9067    8349  20210204

In [18]:
df.iloc[1]

사용일자      20210201
노선명            중앙선
역명              지평
승차총승객수          48
하차총승객수          43
등록일자      20210204
Name: 1, dtype: object

In [19]:
# 인덱스 -> "사용일자"
df2 = df.set_index("사용일자")
df2

          노선명   역명  승차총승객수  하차총승객수      등록일자
사용일자
20210201  중앙선   용문    1282    1259  20210204
20210201  중앙선   지평      48      43  20210204
20210201  중앙선   아신     415     413  20210204
20210201  중앙선   양수    1463    1466  20210204
20210201  중앙선  운길산     495     463  20210204
...       ...  ...     ...     ...       ...
20210228  중앙선   오빈     216     236  20210303
20210228  중앙선   양평    3299    3187  20210303
20210228  중앙선   원덕     322     304  20210303
20210228  중앙선   용문    1899    1716  20210303
20210228  중앙선   지평      30      31  20210303

[16751 rows x 5 columns]

In [20]:
df2.loc[20210201]

          노선명   역명  승차총승객수  하차총승객수      등록일자
사용일자
20210201  중앙선   용문    1282    1259  20210204
20210201  중앙선   지평      48      43  20210204
20210201  중앙선   아신     415     413  20210204
20210201  중앙선   양수    1463    1466  20210204
20210201  중앙선  운길산     495     463  20210204
...       ...  ...     ...     ...       ...
20210201  경원선   도봉    5561    5396  20210204
20210201  1호선  서울역   35821   33113  20210204
20210201  중앙선   신원     166     134  20210204
20210201  8호선   산성    6122    6090  20210204
20210201  중앙선   원덕     273     249  20210204

[599 rows x 5 columns]

3. 2호선 승객수 분석

In [21]:
line2 = df[df['노선명']=='2호선']
print("2호선 승차총승객수 합계 : " , line2['승차총승객수'].sum())
print(df['승차총승객수'].sum())
line2['승차총승객수'].sum()

2호선 승차총승객수 합계 :  28361914
143511591

np.int64(28361914)

In [22]:
df.loc[df['노선명']=='2호선']

           사용일자  노선명         역명  승차총승객수  하차총승객수      등록일자
532    20210201  2호선  용두(동대문구청)    2365    2430  20210204
533    20210201  2호선      신정네거리    9269    9599  20210204
534    20210201  2호선       양천구청    6318    6738  20210204
535    20210201  2호선        도림천    1434    1469  20210204
536    20210201  2호선        신설동    3046    3110  20210204
...         ...  ...        ...     ...     ...       ...
16207  20210228  2호선        신설동    2806    2830  20210303
16208  20210228  2호선        도림천     480     477  20210303
16209  20210228  2호선       양천구청    3234    3281  20210303
16210  20210228  2호선      신정네거리    4814    4805  20210303
16211  20210228  2호선  용두(동대문구청)    1069    1029  20210303

[1400 rows x 6 columns]

4. 혼잡 역사 어디일까 ? = 혼잡 역사 분석

In [23]:
# 1일 승차총승객수 > 50000명 이상이면 혼잡 역으로 분석 

busy_st = df['역명'].loc[df['승차총승객수'] >= 50000]
b_station = busy_st.unique()
b_st_cnt = busy_st.nunique()

print(f"혼잡한 역사는 {b_station}이며 , 총 {b_st_cnt}개이다.")

혼잡한 역사는 ['구로디지털단지' '신림' '강남' '선릉' '잠실(송파구청)' '역삼' '홍대입구' '삼성(무역센터)']이며 , 총 8개이다.

5. 승차총승객수 최대 = 가장 붐비는 총 승차승객수 분석

In [27]:
max_st = df['역명'].loc[df['승차총승객수']==df['승차총승객수'].max()]
max_st = max_st.unique()

print(f"승차총승객수가 가장 많은 역사 : {max_st}")

승차총승객수가 가장 많은 역사 : ['강남']

6. 승차총승객수 최소 분석

In [25]:
min_st = df['역명'].loc[df['승차총승객수']==df['승차총승객수'].min()]
unique_min_st = min_st.unique()

print(f"승차총승객수가 가장 적은 역사 : {unique_min_st}")

승차총승객수가 가장 적은 역사 : ['신내' '연신내' '복정' '계양' '충무로' '창동' '지축' '김포공항' '검암']

In [26]:
df['승차총승객수'].idxmin()

380