데이터 핸들링 
- 데이터 변환 : 데이터 타입 , 인코딩 , 스케일링 , 파생 변수
- 모델이 이해할 수 있는 형태의 데이터 (데이터 프레임) 바꾸는 과정

- astype
- map
- apply
- 범주형 : 원핫인코딩 (문자 => 숫자)
- 스케일링( 표준화/ 정규화 )

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/employee.csv' , index_col = False , encoding = "utf-8-sig")
df.head()

     사번   부서 교육수준  나이  경력    연봉
0  1001   인사   석사  26   0  4074
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627
4  1005   영업   고졸  37  15  5103

### 1. 데이터 구조 분석 
1) 행과 열의 개수

In [3]:
df.shape

(200, 6)

2) 컬럼명

In [4]:
df.columns.tolist()

['사번', '부서', '교육수준', '나이', '경력', '연봉']

3) 자료형

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사번      200 non-null    int64
 1   부서      200 non-null    object
 2   교육수준    200 non-null    object
 3   나이      200 non-null    int64
 4   경력      200 non-null    int64
 5   연봉      200 non-null    int64
dtypes: int64(4), object(2)
memory usage: 9.5+ KB

4) 결측치 파악

In [6]:
df.isnull().sum()

사번      0
부서      0
교육수준    0
나이      0
경력      0
연봉      0
dtype: int64

5) 기초통계량 분석

In [7]:
df.describe

<bound method NDFrame.describe of        사번   부서 교육수준  나이  경력    연봉
0    1001   인사   석사  26   0  4074
1    1002   개발   박사  31   6  5524
2    1003  마케팅   대졸  34  10  5059
3    1004   개발   고졸  45  19  5627
4    1005   영업   고졸  37  15  5103
..    ...  ...  ...  ..  ..   ...
195  1196   영업   대졸  38  13  5527
196  1197   개발   석사  36  11  6255
197  1198  마케팅   대졸  33   7  4504
198  1199   영업   대졸  46  20  6561
199  1200   영업   대졸  35  10  4672

[200 rows x 6 columns]>

6) 범주형 데이터값의 분포 분석

In [8]:
df['부서'].value_counts()

부서
개발     71
영업     71
마케팅    35
인사     23
Name: count, dtype: int64

In [9]:
# 교육수준 데이터 
df['교육수준'].value_counts()

교육수준
대졸    96
석사    52
고졸    45
박사     7
Name: count, dtype: int64

### 2. 결측치 확인 분석 ( 처리 )

In [10]:
# 결측치 확인 
df.isnull().sum()

사번      0
부서      0
교육수준    0
나이      0
경력      0
연봉      0
dtype: int64

In [11]:
# 중복값 확인
df.duplicated().sum()

# 중복값 제거
#df.drop_duplicated()

np.int64(0)

### 3. 자료형 변환

In [12]:
df.dtypes

사번       int64
부서      object
교육수준    object
나이       int64
경력       int64
연봉       int64
dtype: object

In [13]:
df2 = df.copy()
df2

       사번   부서 교육수준  나이  경력    연봉
0    1001   인사   석사  26   0  4074
1    1002   개발   박사  31   6  5524
2    1003  마케팅   대졸  34  10  5059
3    1004   개발   고졸  45  19  5627
4    1005   영업   고졸  37  15  5103
..    ...  ...  ...  ..  ..   ...
195  1196   영업   대졸  38  13  5527
196  1197   개발   석사  36  11  6255
197  1198  마케팅   대졸  33   7  4504
198  1199   영업   대졸  46  20  6561
199  1200   영업   대졸  35  10  4672

[200 rows x 6 columns]

In [14]:
df2['경력'] = df2['경력'].astype(float)   # 자료형 변경

In [15]:
df2['경력'].dtype

dtype('float64')

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사번      200 non-null    int64
 1   부서      200 non-null    object
 2   교육수준    200 non-null    object
 3   나이      200 non-null    int64
 4   경력      200 non-null    float64
 5   연봉      200 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 9.5+ KB

### 4. 값 변환 - map / apply

In [17]:
df3 = df.copy()
df3['교육수준'].unique().tolist()

['석사', '박사', '대졸', '고졸']

In [18]:
edu_level = {
    "고졸" : 1,
    "대졸" : 2,
    "석사" : 3,
    "박사" : 4}

In [19]:
df['교육수준'] = df['교육수준'].map(edu_level)
df

       사번   부서  교육수준  나이  경력    연봉
0    1001   인사     3  26   0  4074
1    1002   개발     4  31   6  5524
2    1003  마케팅     2  34  10  5059
3    1004   개발     1  45  19  5627
4    1005   영업     1  37  15  5103
..    ...  ...   ...  ..  ..   ...
195  1196   영업     2  38  13  5527
196  1197   개발     3  36  11  6255
197  1198  마케팅     2  33   7  4504
198  1199   영업     2  46  20  6561
199  1200   영업     2  35  10  4672

[200 rows x 6 columns]

In [20]:
def 연봉등급(연봉) : 
    if 연봉 >= 6000 : 
        return "상위"
    elif 연봉 >= 4500 : 
        return "중위"
    else : 
        return "하위"

## apply를 이용해서 데이터 적용

In [23]:
df['연봉등급'] = df['연봉'].apply(연봉등급)

In [24]:
df.head()

     사번   부서  교육수준  나이  경력    연봉 연봉등급
0  1001   인사     3  26   0  4074   하위
1  1002   개발     4  31   6  5524   중위
2  1003  마케팅     2  34  10  5059   중위
3  1004   개발     1  45  19  5627   중위
4  1005   영업     1  37  15  5103   중위

### 5. 범주형 인코딩

- 머신러닝은 문자, 비정형 데이터를 읽지 못함 ---> 숫자형 데이터로 핸들링

1) 라벨 인코딩 : 각 범주에 번호를 부여 
2) 원핫 인코딩 : 범주별로 0/1 컬럼 생성 -  디지털 신호로 변환

In [29]:
from sklearn.preprocessing import LabelEncoder # 이후부터 용어 변화 존재

In [28]:
le = LabelEncoder()   # 용어를 변경해서 사용 , 오브젝트 = 생성자

In [32]:
df['연봉등급_라벨'] = le.fit_transform(df['연봉등급']) # 라벨 기준은 자동으로 
df.head()

     사번   부서  교육수준  나이  경력    연봉 연봉등급  연봉등급_라벨
0  1001   인사     3  26   0  4074   하위        2
1  1002   개발     4  31   6  5524   중위        1
2  1003  마케팅     2  34  10  5059   중위        1
3  1004   개발     1  45  19  5627   중위        1
4  1005   영업     1  37  15  5103   중위        1

## 2026 AI : 

학습 -> 학습을 위한 훈련 데이터 
=> 현장에서 얻음

- 머신러닝
    - 트레이닝 ( 필드 )
    - 
    - fitting - 최적의 것을 찾기 위한 Training
    - 
    - Reinforcement ( 강화 학습 )
    -  
- 딥러닝

In [33]:
부서_원핫 = pd.get_dummies(df['부서'],prefix='부서',dtype = int)
부서_원핫.head()

   부서_개발  부서_마케팅  부서_영업  부서_인사
0      0       0      0      1
1      1       0      0      0
2      0       1      0      0
3      1       0      0      0
4      0       0      1      0

In [ ]:
scale = ['나이','경력','연봉']