In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("./data/employee.csv" , index_col = False , encoding = "utf-8")
df.head(10)

     사번   부서 교육수준  나이  경력    연봉
0  1001   인사   석사  26   0  4074
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627
4  1005   영업   고졸  37  15  5103
5  1006  마케팅   대졸  42  16  5762
6  1007   인사   고졸  37  11  4328
7  1008   인사   대졸  26   2  3814
8  1009   영업   고졸  33   8  4999
9  1010   개발   대졸  44  20  6447

In [2]:
df.shape

(200, 6)

## 1. 조건 필터링 - 불리언 인덱싱

In [3]:
high_salary = df[df['연봉'] >= 5000 ]
print(f"연봉 5000 이상 : {len(high_salary)}명")
print(high_salary.head(3))

연봉 5000 이상 : 108명
     사번   부서 교육수준  나이  경력    연봉
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627

## 2. 여러 조건 결합 - AND(&) , OR(|)

In [4]:
# AND  : 개발 부서이면서 연봉이 5000 이상

dev_high_salary = df[ (df['부서']=="개발") & (df['연봉'] >= 5000) ]
print(f"개발 부서이면서 연봉이 5000 이상 : {len(dev_high_salary)}명")
print(dev_high_salary.head(5))

개발 부서이면서 연봉이 5000 이상 : 47명
      사번  부서 교육수준  나이  경력    연봉
1   1002  개발   박사  31   6  5524
3   1004  개발   고졸  45  19  5627
9   1010  개발   대졸  44  20  6447
12  1013  개발   고졸  37  14  6083
14  1015  개발   석사  40  16  6675

In [5]:
# OR : 박사 또는 경력 15년 이상 

x = df[(df['교육수준']=="박사") | (df['경력'] >= 15)]
print(f"박사이거나 경력이 15년 이상인 직원 : {len(x)}명")
print(x.head(5))

박사이거나 경력이 15년 이상인 직원 : 57명
     사번   부서 교육수준  나이  경력    연봉
1  1002   개발   박사  31   6  5524
3  1004   개발   고졸  45  19  5627
4  1005   영업   고졸  37  15  5103
5  1006  마케팅   대졸  42  16  5762
9  1010   개발   대졸  44  20  6447

In [6]:
# NOT 인사부서가 아닌 인원

non_hire = df[df["부서"] != "인사"]
print(f"인사 부서가 아닌 인원 : {len(non_hire)}명")
print(non_hire.head(5))

인사 부서가 아닌 인원 : 177명
     사번   부서 교육수준  나이  경력    연봉
1  1002   개발   박사  31   6  5524
2  1003  마케팅   대졸  34  10  5059
3  1004   개발   고졸  45  19  5627
4  1005   영업   고졸  37  15  5103
5  1006  마케팅   대졸  42  16  5762

## 3. isin/between - 편리한 필터링

In [7]:
# isin : 목록에 포함되는 값 
# 영업 , 마케팅 부서 

em = len(df[df['부서'].isin(['영업','마케팅'])])
em

106

In [8]:
# between : 

em_y = len(df[df['경력'].between(5,10)])
em_y

52

## 4. query() - 조건을 문장처럼

In [9]:
result = df.query("부서 == '개발' and 연봉 >= 4500 and 경력 < 10") # "" 안에 '' 
print(f"조건 만족 : {len(result)}명")
result.head()

조건 만족 : 15명

       사번  부서 교육수준  나이  경력    연봉
1    1002  개발   박사  31   6  5524
37   1038  개발   석사  26   4  4558
40   1041  개발   석사  31   6  5172
53   1054  개발   대졸  31   5  5033
106  1107  개발   대졸  31   8  4844

### 5. 정렬  - sort_values

In [10]:
# 연봉 Top 3 내림차순 

salary_top = df.sort_values(by = ["연봉"],ascending = False).head(3)[["사번","부서","연봉"]]
print(f"연봉 Top 3 멤버 : \n {salary_top}")

연봉 Top 3 멤버 :
        사번  부서    연봉
61   1062  개발  7224
148  1149  개발  7088
164  1165  개발  7006

In [11]:
# 연봉 Top3 (내림차순)

res = df.sort_values(by="연봉",ascending= False)
res.head(3)

       사번  부서 교육수준  나이  경력    연봉
61   1062  개발   석사  44  19  7224
148  1149  개발   대졸  44  19  7088
164  1165  개발   대졸  43  19  7006

In [12]:
#같은 부서 안에서 많은 사람부터 정렬



for i in res['부서'].unique():
    res = df[df['부서']==i].sort_values(by="연봉",ascending= False)[:3]
    print(f"부서 : {i}\n\n",res)

부서 : 개발

        사번  부서 교육수준  나이  경력    연봉
61   1062  개발   석사  44  19  7224
148  1149  개발   대졸  44  19  7088
164  1165  개발   대졸  43  19  7006
부서 : 영업

        사번  부서 교육수준  나이  경력    연봉
15   1016  영업   석사  43  17  6996
50   1051  영업   대졸  44  20  6909
168  1169  영업   대졸  45  19  6629
부서 : 인사

        사번  부서 교육수준  나이  경력    연봉
42   1043  인사   대졸  43  19  6585
158  1159  인사   대졸  43  20  6347
55   1056  인사   석사  43  17  6128
부서 : 마케팅

        사번   부서 교육수준  나이  경력    연봉
23   1024  마케팅   박사  39  13  6455
103  1104  마케팅   대졸  40  18  6395
142  1143  마케팅   석사  45  19  6393

In [13]:
# nlargest / nsmallest ( 정렬 대신 간편하게 데이터를 핸들링 정렬이 필요할때 사용)

df.nlargest(3,["연봉","나이"])[["사번","연봉","나이"]]

       사번    연봉  나이
61   1062  7224  44
148  1149  7088  44
164  1165  7006  43

In [14]:
df.nsmallest(3,"연봉")[["사번","연봉"]]

      사번    연봉
38  1039  2815
88  1089  2988
16  1017  3004