## 프로젝트 1. 이커머스 주문 데이터 분석 프로젝트

### 사용 데이터

- `project2_customers.csv`
- `project2_products.csv`
- `project2_orders_q1.csv`
- `project2_orders_q2.csv`

### 프로젝트 상황

이커머스 기업에서 2026년 상반기 주문 데이터를 분석하여 매출, 이익, 고객 특성별 구매 패턴을 확인하려고 합니다.

### 수행 조건

1. 고객, 상품, Q1 주문, Q2 주문 데이터를 불러오시오.
2. Q1 주문 데이터와 Q2 주문 데이터를 `concat`으로 합치시오.
3. 결측치와 중복치를 확인하고 처리하시오.
4. 주문일자를 날짜형으로 변환하고 주문월, 요일 변수를 생성하시오.
5. 주문 데이터에 고객 정보를 `merge`하시오.
6. 주문 데이터에 상품 정보를 `merge`하시오.
7. `join`을 사용하여 주문 데이터에 상품 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.
8. `iloc`로 앞 5행과 일부 컬럼을 선택하시오.
8. `loc`로 VIP 고객 주문만 선택하시오.
9. 총매출액, 할인액, 순매출액, 이익, 실매출액 변수를 생성하시오.
10. 전자기기 카테고리의 고액 정상 주문을 필터링하고 정렬하시오.
11. 카테고리별 주문건수, 판매수량, 실매출액, 실이익을 집계하시오.
12. 회원등급을 순서형 인코딩하시오.
13. 카테고리, 지역, 결제수단, 판매채널을 원-핫 인코딩하시오.
14. 매출 관련 수치형 컬럼을 스케일링하시오.
15. 최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.

## 프로젝트 2. 스마트팩토리 생산 품질 데이터 분석 프로젝트

### 사용 데이터

- `project3_production_jan.csv`
- `project3_production_feb.csv`
- `project3_production_mar.csv`
- `project3_machine_info.csv`
- `project3_operator_info.csv`

### 프로젝트 상황

제조기업에서 월별 생산 데이터, 설비 정보, 작업자 정보를 통합하여 불량률이 높은 조건을 파악하고 품질 분석용 데이터셋을 만들려고 합니다.

### 수행 조건

1. 1월, 2월, 3월 생산 데이터를 불러오시오.
2. 월별 생산 데이터를 `concat`으로 합치시오.
3. 데이터 구조, 결측치, 중복치를 확인하시오.
4. 중복치를 제거하시오.
5. 온도, 압력, 진동 결측치를 중앙값으로 처리하시오.
6. IQR 방식으로 진동 이상치를 확인하고 보정하시오.
7. 생산일자를 날짜형으로 변환하고 생산월, 생산요일을 생성하시오.
8. 생산 데이터와 설비 정보를 `merge`하시오.
9. 생산 데이터와 작업자 정보를 `merge`하시오.
10. `join`을 사용하여 생산 데이터에 설비 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.
11. `iloc`로 앞 5행과 일부 컬럼을 선택하시오.
11. `loc`로 야간 생산 데이터만 선택하시오.
12. 양품수량, 불량률, 설비연식, 고불량여부 변수를 생성하시오.
13. 불량률이 높은 야간 생산 데이터를 필터링하고 정렬하시오.
14. 라인과 교대별 평균 불량률을 집계하시오.
15. 숙련도를 순서형 인코딩하시오.
16. 제품유형, 교대, 라인, 설비유형을 원-핫 인코딩하시오.
17. 생산수량, 불량수량, 온도, 압력, 진동, 불량률을 스케일링하시오.
18. 최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.

In [1]:
import pandas as pd
import numpy as np

# 범주형 데이터 변환 
from sklearn.preprocessing import LabelEncoder # 이후부터 용어 변화 존재 

# 데이터 시각화 분석 라이브러리 
import matplotlib.pyplot as plt

# 한글 패치 표준

plt.rcParams['font.family'] = 'Malgun Gothic' # apple : 'AppleGothic'

# 마이너스 부호 깨짐 방지
import matplotlib.pyplot as plt
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 1월, 2월, 3월 생산 데이터를 불러오시오.

jan = pd.read_csv("./data/project3_production_jan.csv")
feb = pd.read_csv("./data/project3_production_feb.csv")
mar = pd.read_csv("./data/project3_production_mar.csv")

jan
feb
mar

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량
0,MAR-00001,2026-03-15,M10,OP005,기어,주간,96,55.0,88.8,2.03,54.6,2
1,MAR-00002,2026-03-17,M04,OP018,샤프트,주간,193,59.2,102.0,2.05,48.8,3
2,MAR-00003,2026-03-04,M02,OP025,기어,주간,124,NaN,112.8,3.29,40.9,2
3,MAR-00004,2026-03-25,M02,OP015,브라켓,야간,201,53.3,110.0,3.63,61.7,7
4,MAR-00005,2026-03-07,M08,OP001,샤프트,주간,172,51.0,94.4,3.17,60.9,2
...,...,...,...,...,...,...,...,...,...,...,...,...
379,MAR-00380,2026-03-17,M02,OP005,기어,야간,205,49.7,97.9,2.01,40.4,4
380,MAR-00188,2026-03-06,M04,OP005,하우징,야간,104,48.2,120.3,3.82,50.1,3
381,MAR-00211,2026-03-10,M07,OP001,샤프트,야간,97,50.3,102.6,4.03,46.7,3
382,MAR-00314,2026-03-05,M06,OP024,브라켓,주간,187,49.5,93.9,2.66,51.6,4
383,MAR-00236,2026-03-12,M12,OP004,기어,야간,187,49.3,119.3,1.51,40.3,4

In [3]:
# 월별 생산 데이터를 concat으로 합치시오.

pro_df = pd.concat([jan,feb,mar],ignore_index = True)
pro_df

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65,44.1,6
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10,47.2,5
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23,58.1,4
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10,59.9,2
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18,53.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1069,MAR-00380,2026-03-17,M02,OP005,기어,야간,205,49.7,97.9,2.01,40.4,4
1070,MAR-00188,2026-03-06,M04,OP005,하우징,야간,104,48.2,120.3,3.82,50.1,3
1071,MAR-00211,2026-03-10,M07,OP001,샤프트,야간,97,50.3,102.6,4.03,46.7,3
1072,MAR-00314,2026-03-05,M06,OP024,브라켓,주간,187,49.5,93.9,2.66,51.6,4
1073,MAR-00236,2026-03-12,M12,OP004,기어,야간,187,49.3,119.3,1.51,40.3,4

In [4]:
# 데이터 구조, 결측치, 중복치를 확인하시오.

# 데이터 구조 
pro_df.dtypes

생산ID      object
생산일자      object
설비ID      object
작업자ID     object
제품유형      object
교대        object
생산수량       int64
온도       float64
압력       float64
진동       float64
사이클타임    float64
불량수량       int64
dtype: object

In [5]:
# 결측치

pro_df.isnull().sum()

생산ID     0
생산일자     0
설비ID     0
작업자ID    0
제품유형     0
교대       0
생산수량     0
온도       9
압력       6
진동       9
사이클타임    0
불량수량     0
dtype: int64

In [6]:
# 중복치
pro_df.duplicated().sum()

np.int64(4)

In [7]:
# 중복치를 제거하시오.
pro_df.drop_duplicates(inplace = True)

pro_df

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65,44.1,6
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10,47.2,5
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23,58.1,4
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10,59.9,2
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18,53.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1065,MAR-00376,2026-03-31,M04,OP027,브라켓,주간,88,54.3,101.7,3.28,46.4,2
1066,MAR-00377,2026-03-04,M07,OP030,브라켓,야간,176,46.0,94.0,9.20,51.0,4
1067,MAR-00378,2026-03-02,M03,OP028,샤프트,야간,142,56.8,99.8,3.04,51.4,4
1068,MAR-00379,2026-03-04,M03,OP020,샤프트,주간,236,56.6,83.4,4.44,40.6,10
1069,MAR-00380,2026-03-17,M02,OP005,기어,야간,205,49.7,97.9,2.01,40.4,4

In [8]:
# 중복치 제거 확인

pro_df.duplicated().sum()

np.int64(0)

In [9]:
# 5. 온도, 압력, 진동 결측치를 중앙값으로 처리하시오.

pro_df['온도'].fillna(pro_df['온도'].median(),inplace=True)
pro_df['압력'].fillna(pro_df['압력'].median(),inplace=True)
pro_df['진동'].fillna(pro_df['진동'].median(),inplace=True)

C:\Users\최영준\AppData\Local\Temp\ipykernel_23888\3410440435.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro_df['온도'].fillna(pro_df['온도'].median(),inplace=True)
C:\Users\최영준\AppData\Local\Temp\ipykernel_23888\3410440435.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro_df['압력'].fillna(pro_df['압력'].median(),inplace=True)
C:\Users\최영준\AppData\Local\Temp\ipykernel_23888\3410440435.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pro_df['진동'].fillna(pro_df['진동'].median(),inplace=True)

In [10]:
pro_df['온도'].isnull().sum()

np.int64(0)

In [11]:
pro_df['압력'].isnull().sum()

np.int64(0)

In [12]:
pro_df['진동'].isnull().sum()

np.int64(0)

In [13]:
# IQR 방식으로 진동 이상치를 확인하고 보정하시오.

Q1 = pro_df["진동"].quantile(0.25)
Q3 = pro_df["진동"].quantile(0.75)

IQR = Q3 - Q1

Lower = Q1 - 1.5 * IQR
Upper = Q3 + 1.5 * IQR

# 이상치 확인 Upper
pro_df[pro_df['진동'] >= Upper]

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량
120,JAN-00121,2026-01-26,M02,OP026,브라켓,주간,201,61.8,113.5,5.29,41.9,5
149,JAN-00150,2026-01-05,M03,OP011,샤프트,주간,111,64.6,92.8,5.62,58.7,4
248,JAN-00249,2026-01-20,M08,OP010,샤프트,주간,168,65.3,98.3,5.76,45.1,3
758,MAR-00069,2026-03-09,M10,OP001,기어,주간,154,49.5,80.7,5.33,49.3,4
800,MAR-00111,2026-03-06,M05,OP013,기어,야간,126,54.6,88.3,10.10,39.9,4
814,MAR-00125,2026-03-10,M05,OP029,샤프트,주간,125,45.8,102.8,8.50,48.7,1
816,MAR-00127,2026-03-21,M09,OP004,샤프트,야간,166,49.2,104.8,5.73,47.2,6
894,MAR-00205,2026-03-09,M04,OP030,샤프트,야간,112,64.2,102.0,5.44,40.3,2
1066,MAR-00377,2026-03-04,M07,OP030,브라켓,야간,176,46.0,94.0,9.20,51.0,4

In [14]:
# 이상치 확인 Lower

pro_df[pro_df['진동'] <= Lower]

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량
47,JAN-00048,2026-01-20,M04,OP005,샤프트,야간,152,52.2,118.1,1.10,35.4,4
162,JAN-00163,2026-01-04,M03,OP017,기어,주간,238,53.7,106.9,0.73,56.7,5
277,JAN-00278,2026-01-04,M11,OP013,하우징,야간,150,56.8,99.3,0.78,58.2,2
395,FEB-00036,2026-02-26,M04,OP010,브라켓,주간,113,59.9,96.7,1.15,50.2,1
568,FEB-00209,2026-02-08,M06,OP008,하우징,주간,177,55.0,111.8,1.20,46.5,4
574,FEB-00215,2026-02-22,M03,OP020,하우징,주간,233,57.0,109.9,0.94,46.9,4
577,FEB-00218,2026-02-09,M09,OP020,하우징,야간,230,54.8,128.1,0.62,43.8,5
648,FEB-00289,2026-02-05,M08,OP011,기어,야간,171,57.2,112.5,1.19,48.7,5
806,MAR-00117,2026-03-23,M07,OP021,하우징,야간,185,59.8,104.7,1.21,48.5,5
815,MAR-00126,2026-03-31,M12,OP016,브라켓,야간,158,46.2,114.4,1.18,51.9,4
903,MAR-00214,2026-03-02,M09,OP001,샤프트,주간,128,54.7,108.4,1.21,48.4,2

In [15]:
# outlier_df = pro_df.copy() 
# 검증용

In [16]:
def 이상치보정(진동) :
    if 진동 >= Upper : 
        return Upper 
    elif 진동 <= Lower : 
        return Lower
    else :
        return 진동

In [17]:
# 이상치 보정

pro_df['진동'] = pro_df['진동'].apply(이상치보정)
pro_df

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65000,44.1,6
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10000,47.2,5
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23000,58.1,4
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10000,59.9,2
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18000,53.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1065,MAR-00376,2026-03-31,M04,OP027,브라켓,주간,88,54.3,101.7,3.28000,46.4,2
1066,MAR-00377,2026-03-04,M07,OP030,브라켓,야간,176,46.0,94.0,5.18125,51.0,4
1067,MAR-00378,2026-03-02,M03,OP028,샤프트,야간,142,56.8,99.8,3.04000,51.4,4
1068,MAR-00379,2026-03-04,M03,OP020,샤프트,주간,236,56.6,83.4,4.44000,40.6,10
1069,MAR-00380,2026-03-17,M02,OP005,기어,야간,205,49.7,97.9,2.01000,40.4,4

In [18]:
# 이상치 확인 Upper
pro_df[pro_df['진동'] > Upper].sum()

생산ID       0
생산일자       0
설비ID       0
작업자ID      0
제품유형       0
교대         0
생산수량       0
온도       0.0
압력       0.0
진동       0.0
사이클타임    0.0
불량수량       0
dtype: object

In [19]:
# 이상치 확인 Lower
pro_df[pro_df['진동'] < Lower].sum()

생산ID       0
생산일자       0
설비ID       0
작업자ID      0
제품유형       0
교대         0
생산수량       0
온도       0.0
압력       0.0
진동       0.0
사이클타임    0.0
불량수량       0
dtype: object

In [20]:
# 생산일자를 날짜형으로 변환하고 생산월, 생산요일을 생성하시오.

pro_df['생산일자'] = pd.to_datetime(pro_df['생산일자'])
pro_df['생산일자'].dtype

dtype('<M8[ns]')

In [21]:
pro_df['생산월'] = pro_df['생산일자'].dt.month

In [22]:
pro_df['생산요일'] = pro_df['생산일자'].dt.weekday

In [23]:
pro_df

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량,생산월,생산요일
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65000,44.1,6,1,0
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10000,47.2,5,1,0
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23000,58.1,4,1,3
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10000,59.9,2,1,6
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18000,53.6,6,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,MAR-00376,2026-03-31,M04,OP027,브라켓,주간,88,54.3,101.7,3.28000,46.4,2,3,1
1066,MAR-00377,2026-03-04,M07,OP030,브라켓,야간,176,46.0,94.0,5.18125,51.0,4,3,2
1067,MAR-00378,2026-03-02,M03,OP028,샤프트,야간,142,56.8,99.8,3.04000,51.4,4,3,0
1068,MAR-00379,2026-03-04,M03,OP020,샤프트,주간,236,56.6,83.4,4.44000,40.6,10,3,2
1069,MAR-00380,2026-03-17,M02,OP005,기어,야간,205,49.7,97.9,2.01000,40.4,4,3,1

In [24]:
# 설비 정보 import .

machine_info = pd.read_csv("./data/project3_machine_info.csv",index_col = False, encoding = 'utf-8')
machine_info.head()

  설비ID  라인 설비유형         제조사  도입연도
0  M01  L3  검사기      K-Tech  2022
1  M02  L1  CNC     M-Works  2023
2  M03  L3  CNC     M-Works  2022
3  M04  L3  포장기      K-Tech  2019
4  M05  L3  조립기  AI-Machine  2021

In [25]:
# 생산 데이터와 설비 정보를 merge하시오.

machine_prod = pd.merge(pro_df,machine_info, on = '설비ID' ,how = 'inner')
machine_prod.head()

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량,생산월,생산요일,라인,설비유형,제조사,도입연도
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65,44.1,6,1,0,L2,CNC,K-Tech,2019
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10,47.2,5,1,0,L3,조립기,K-Tech,2019
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23,58.1,4,1,3,L3,조립기,K-Tech,2019
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10,59.9,2,1,6,L1,CNC,M-Works,2023
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18,53.6,6,1,0,L3,포장기,M-Works,2024

In [26]:
# 작업자 정보 import 

operator_info = pd.read_csv("./data/project3_operator_info.csv",index_col = False , encoding = 'utf-8')
operator_info.head()

   작업자ID 작업조 숙련도
0  OP001  A조  초급
1  OP002  A조  중급
2  OP003  A조  중급
3  OP004  A조  고급
4  OP005  B조  중급

In [32]:
# 생산 데이터와 작업자 정보를 merge하시오.

df = pd.merge(machine_prod,operator_info, on = '작업자ID' , how = 'inner')
df.head()

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량,생산월,생산요일,라인,설비유형,제조사,도입연도,작업조,숙련도
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65,44.1,6,1,0,L2,CNC,K-Tech,2019,B조,중급
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10,47.2,5,1,0,L3,조립기,K-Tech,2019,B조,고급
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23,58.1,4,1,3,L3,조립기,K-Tech,2019,C조,중급
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10,59.9,2,1,6,L1,CNC,M-Works,2023,C조,초급
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18,53.6,6,1,0,L3,포장기,M-Works,2024,B조,중급

In [28]:
# join을 사용하여 생산 데이터에 설비 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.

machine_prod = pd.merge(pro_df,machine_info, left_on = '설비ID' ,right_index = True)
machine_prod.head()

ValueError: You are trying to merge on object and int64 columns for key '설비ID'. If you wish to proceed you should use pd.concat

In [33]:
# iloc로 앞 5행과 일부 컬럼을 선택하시오.

df.iloc[:5]

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량,생산월,생산요일,라인,설비유형,제조사,도입연도,작업조,숙련도
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65,44.1,6,1,0,L2,CNC,K-Tech,2019,B조,중급
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10,47.2,5,1,0,L3,조립기,K-Tech,2019,B조,고급
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23,58.1,4,1,3,L3,조립기,K-Tech,2019,C조,중급
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10,59.9,2,1,6,L1,CNC,M-Works,2023,C조,초급
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18,53.6,6,1,0,L3,포장기,M-Works,2024,B조,중급

In [34]:
# loc로 야간 생산 데이터만 선택하시오.

df.loc[pro_df['교대']=='야간']

,생산ID,생산일자,설비ID,작업자ID,제품유형,교대,생산수량,온도,압력,진동,사이클타임,불량수량,생산월,생산요일,라인,설비유형,제조사,도입연도,작업조,숙련도
0,JAN-00001,2026-01-12,M11,OP021,기어,야간,235,57.7,114.5,3.65000,44.1,6,1,0,L2,CNC,K-Tech,2019,B조,중급
1,JAN-00002,2026-01-26,M12,OP006,브라켓,야간,109,50.4,101.1,4.10000,47.2,5,1,0,L3,조립기,K-Tech,2019,B조,고급
2,JAN-00003,2026-01-29,M12,OP010,샤프트,야간,132,58.2,93.9,2.23000,58.1,4,1,3,L3,조립기,K-Tech,2019,C조,중급
3,JAN-00004,2026-01-04,M02,OP024,하우징,야간,96,60.2,116.0,3.10000,59.9,2,1,6,L1,CNC,M-Works,2023,C조,초급
4,JAN-00005,2026-01-26,M06,OP030,샤프트,야간,230,51.5,98.4,4.18000,53.6,6,1,0,L3,포장기,M-Works,2024,B조,중급
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,MAR-00374,2026-03-02,M11,OP004,브라켓,야간,218,56.2,112.1,2.74000,41.6,6,3,0,L2,CNC,K-Tech,2019,A조,고급
1064,MAR-00375,2026-03-19,M08,OP013,기어,야간,223,57.2,112.2,3.66000,50.6,5,3,3,L3,검사기,K-Tech,2024,B조,고급
1066,MAR-00377,2026-03-04,M07,OP030,브라켓,야간,176,46.0,94.0,5.18125,51.0,4,3,2,L2,조립기,K-Tech,2015,B조,중급
1067,MAR-00378,2026-03-02,M03,OP028,샤프트,야간,142,56.8,99.8,3.04000,51.4,4,3,0,L3,CNC,M-Works,2022,B조,초급
1069,MAR-00380,2026-03-17,M02,OP005,기어,야간,205,49.7,97.9,2.01000,40.4,4,3,1,L1,CNC,M-Works,2023,B조,중급

In [39]:
# 양품수량, 불량률, 설비연식, 고불량여부 변수를 생성하시오.

양품수량 = df['생산수량'] - df['불량수량']
print(양품수량)

불량률 = df['불량수량'] / df['생산수량']
print(불량률)

설비연식 = df['생산일자'].dt.year - df['도입연도']
print(설비연식)

고불량여부 =

SyntaxError: invalid syntax (1767528294.py, line 12)

In [38]:
df['불량수량'].unique()

array([ 6,  5,  4,  2,  3,  1,  7,  8,  9, 12,  0, 10])