## 프로젝트 1. 이커머스 주문 데이터 분석 프로젝트

### 사용 데이터

- `project2_customers.csv`
- `project2_products.csv`
- `project2_orders_q1.csv`
- `project2_orders_q2.csv`

### 프로젝트 상황

이커머스 기업에서 2026년 상반기 주문 데이터를 분석하여 매출, 이익, 고객 특성별 구매 패턴을 확인하려고 합니다.

### 수행 조건

1. 고객, 상품, Q1 주문, Q2 주문 데이터를 불러오시오.
2. Q1 주문 데이터와 Q2 주문 데이터를 `concat`으로 합치시오.
3. 결측치와 중복치를 확인하고 처리하시오.
4. 주문일자를 날짜형으로 변환하고 주문월, 요일 변수를 생성하시오.
5. 주문 데이터에 고객 정보를 `merge`하시오.
6. 주문 데이터에 상품 정보를 `merge`하시오.
7. `join`을 사용하여 주문 데이터에 상품 정보를 인덱스 기준으로 붙이는 예제를 작성하시오.
8. `iloc`로 앞 5행과 일부 컬럼을 선택하시오.
8. `loc`로 VIP 고객 주문만 선택하시오.
9. 총매출액, 할인액, 순매출액, 이익, 실매출액 변수를 생성하시오.
10. 전자기기 카테고리의 고액 정상 주문을 필터링하고 정렬하시오.
11. 카테고리별 주문건수, 판매수량, 실매출액, 실이익을 집계하시오.
12. 회원등급을 순서형 인코딩하시오.
13. 카테고리, 지역, 결제수단, 판매채널을 원-핫 인코딩하시오.
14. 매출 관련 수치형 컬럼을 스케일링하시오.
15. 최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.

In [1]:
import pandas as pd

# 데이터 시각화 분석 라이브러리 
import matplotlib.pyplot as plt

# 한글 패치 표준

plt.rcParams['font.family'] = 'Malgun Gothic' # apple : 'AppleGothic'

# 마이너스 부호 깨짐 방지
import matplotlib.pyplot as plt
plt.rcParams['axes.unicode_minus'] = False

### 이커머스 기업에서 2026년 상반기 주문 데이터를 분석하여 매출, 이익, 고객 특성별 구매 패턴을 확인하려고 합니다.

In [2]:
# 고객, 상품, Q1 주문, Q2 주문 데이터를 불러오시오.

customers = pd.read_csv("./data/project2_customers.csv",index_col = False , encoding = 'utf-8')
products = pd.read_csv("./data/project2_products.csv",index_col = False , encoding = 'utf-8')
orders_q1 = pd.read_csv("./data/project2_orders_q1.csv",index_col = False , encoding = 'utf-8')
orders_q2 = pd.read_csv("./data/project2_orders_q2.csv",index_col = False , encoding = 'utf-8')

In [3]:
# 주문 데이터 확인

orders_q1

         주문ID        주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부
0    Q1-00001  2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상
1    Q1-00002  2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상
2    Q1-00003  2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상
3    Q1-00004  2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상
4    Q1-00005  2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상
..        ...         ...   ...   ...  ..   ...   ...   ...  ...
460  Q1-00283  2026-02-01  2133  3019   2  0.20    카드     웹   정상
461  Q1-00198  2026-02-17  2120  3022   5  0.00  간편결제  오프라인   정상
462  Q1-00202  2026-01-08  2159  3019   4  0.00    카드  모바일앱   정상
463  Q1-00219  2026-01-14  2141  3044   2  0.10    카드  모바일앱   정상
464  Q1-00411  2026-03-26  2143  3052   4  0.15    카드  모바일앱   정상

[465 rows x 9 columns]

In [4]:
orders_q2

         주문ID        주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부
0    Q2-00001  2026-06-26  2009  3012   4  0.05    카드  모바일앱   환불
1    Q2-00002  2026-05-04  2081  3020   4  0.00    카드  모바일앱   정상
2    Q2-00003  2026-06-15  2059  3017   1  0.05   무통장  모바일앱   정상
3    Q2-00004  2026-05-13  2022  3037   4  0.10  간편결제  모바일앱   정상
4    Q2-00005  2026-06-05  2110  3049   5  0.10  계좌이체  오프라인   정상
..        ...         ...   ...   ...  ..   ...   ...   ...  ...
510  Q2-00483  2026-06-29  2103  3023   3  0.20   무통장  모바일앱   정상
511  Q2-00358  2026-06-11  2070  3045   5  0.15  간편결제  오프라인   정상
512  Q2-00510  2026-04-21  2103  3037   4  0.15    카드  모바일앱   정상
513  Q2-00299  2026-04-11  2005  3019   4  0.00    카드     웹   정상
514  Q2-00211  2026-05-06  2019  3042   5  0.05  간편결제  모바일앱   정상

[515 rows x 9 columns]

In [5]:
# Q1 주문 데이터와 Q2 주문 데이터 결합

orders = pd.concat( [orders_q1,orders_q2],ignore_index = True )
orders.sort_values("주문ID")

         주문ID        주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부
0    Q1-00001  2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상
1    Q1-00002  2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상
2    Q1-00003  2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상
3    Q1-00004  2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상
4    Q1-00005  2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상
..        ...         ...   ...   ...  ..   ...   ...   ...  ...
971  Q2-00507  2026-06-18  2113  3012   5  0.00   무통장  모바일앱   정상
972  Q2-00508  2026-05-13  2135  3021   4  0.10  간편결제     웹   정상
973  Q2-00509  2026-04-01  2046  3039   5  0.15   무통장     웹   정상
974  Q2-00510  2026-04-21  2103  3037   4  0.15    카드  모바일앱   정상
977  Q2-00510  2026-04-21  2103  3037   4  0.15    카드  모바일앱   정상

[980 rows x 9 columns]

In [6]:
# 데이터 구조 확인
orders.dtypes

주문ID     object
주문일자     object
고객ID      int64
상품ID      int64
수량        int64
할인율     float64
결제수단     object
판매채널     object
환불여부     object
dtype: object

In [7]:
# 결측치 확인
orders.isnull().sum()

주문ID     0
주문일자     0
고객ID     0
상품ID     0
수량       0
할인율     37
결제수단     0
판매채널     0
환불여부     0
dtype: int64

In [8]:
# 결측치 처리 - 평균 
orders['할인율'] = orders['할인율'].fillna(orders['할인율'].mean())
orders.isnull().sum()

주문ID    0
주문일자    0
고객ID    0
상품ID    0
수량      0
할인율     0
결제수단    0
판매채널    0
환불여부    0
dtype: int64

In [9]:
# 중복치 확인 

orders.duplicated().sum()

np.int64(10)

In [10]:
# 중복치 처리 - 제거

orders.drop_duplicates(inplace = True)
orders.duplicated().sum()

np.int64(0)

In [11]:
# 주문일자 자료형 변환

orders['주문일자'] = pd.to_datetime(orders['주문일자'])
orders['주문일자'].dtype

dtype('<M8[ns]')

In [12]:
# 주문월 변수 생성

orders['주문월'] = orders['주문일자'].dt.month.astype(str) + "월"
orders.head()

       주문ID       주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부 주문월
0  Q1-00001 2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상  2월
1  Q1-00002 2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상  2월
2  Q1-00003 2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상  1월
3  Q1-00004 2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상  3월
4  Q1-00005 2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상  2월

In [13]:
# 주문 요일 변수 생성 
orders['주문요일'] = orders['주문일자'].dt.weekday

week_day = {
    0 : "월요일",
    1 : "화요일",
    2 : "수요일",
    3 : "목요일",
    4 : "금요일",
    5 : "토요일",
    6 : "일요일"
}

orders['주문요일'] = orders['주문요일'].map(week_day)
orders.head()

       주문ID       주문일자  고객ID  상품ID  수량   할인율  결제수단  판매채널 환불여부 주문월 주문요일
0  Q1-00001 2026-02-12  2057  3045   4  0.10  간편결제  모바일앱   정상  2월  목요일
1  Q1-00002 2026-02-22  2054  3044   3  0.10    카드  모바일앱   정상  2월  일요일
2  Q1-00003 2026-01-30  2084  3048   4  0.05    카드  모바일앱   정상  1월  금요일
3  Q1-00004 2026-03-05  2091  3001   3  0.20  계좌이체  모바일앱   정상  3월  목요일
4  Q1-00005 2026-02-28  2142  3027   4  0.05  계좌이체     웹   정상  2월  토요일

In [14]:
# 주문 데이터에 고객 정보 merge

orders = pd.merge(orders , customers , on = "고객ID")
orders.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,성별,연령,지역,회원등급
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2월,목요일,여성,18,경상,일반
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2월,일요일,여성,42,전라,일반
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1월,금요일,남성,31,경기,실버
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3월,목요일,남성,30,충청,일반
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2월,토요일,여성,27,서울,VIP

In [15]:
# 주문 데이터에 상품 정보 merge

orders = pd.merge(orders,products,on = "상품ID")
orders.head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,성별,연령,지역,회원등급,카테고리,브랜드,원가,판매가
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2월,목요일,여성,18,경상,일반,식품,C브랜드,9809,16670
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2월,일요일,여성,42,전라,일반,식품,C브랜드,10960,20808
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1월,금요일,남성,31,경기,실버,패션,D브랜드,36520,67712
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3월,목요일,남성,30,충청,일반,패션,A브랜드,39896,61987
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2월,토요일,여성,27,서울,VIP,식품,D브랜드,10234,22248

In [16]:
# join을 사용하여 주문 데이터에 상품 정보를 인덱스 기준으로 붙이는 예제 작성.

prod_index_order = pd.merge(orders,products,on = "상품ID").set_index("상품ID").sort_index()
prod_index_order.head()

,주문ID,주문일자,고객ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,...,지역,회원등급,카테고리_x,브랜드_x,원가_x,판매가_x,카테고리_y,브랜드_y,원가_y,판매가_y
상품ID,,,,,,,,,,,,,,,,,,,,,
3001,Q2-00469,2026-04-13,2044,3,0.05,간편결제,모바일앱,정상,4월,월요일,...,경기,실버,패션,A브랜드,39896,61987,패션,A브랜드,39896,61987
3001,Q2-00241,2026-05-04,2103,1,0.00,계좌이체,웹,정상,5월,월요일,...,서울,VIP,패션,A브랜드,39896,61987,패션,A브랜드,39896,61987
3001,Q1-00450,2026-01-07,2084,5,0.10,카드,모바일앱,정상,1월,수요일,...,경기,실버,패션,A브랜드,39896,61987,패션,A브랜드,39896,61987
3001,Q1-00096,2026-03-14,2107,1,0.10,간편결제,웹,정상,3월,토요일,...,경상,실버,패션,A브랜드,39896,61987,패션,A브랜드,39896,61987
3001,Q2-00496,2026-04-19,2062,4,0.00,간편결제,웹,정상,4월,일요일,...,경기,일반,패션,A브랜드,39896,61987,패션,A브랜드,39896,61987

In [17]:
# iloc로 앞 5행과 일부 컬럼을 선택

orders.iloc[:5,[1,2,3,4,5,6]]

        주문일자  고객ID  상품ID  수량   할인율  결제수단
0 2026-02-12  2057  3045   4  0.10  간편결제
1 2026-02-22  2054  3044   3  0.10    카드
2 2026-01-30  2084  3048   4  0.05    카드
3 2026-03-05  2091  3001   3  0.20  계좌이체
4 2026-02-28  2142  3027   4  0.05  계좌이체

In [18]:
# loc로 VIP 고객 주문만 선택하시오.

orders.loc[orders["회원등급"]=="VIP"].head()

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,주문요일,성별,연령,지역,회원등급,카테고리,브랜드,원가,판매가
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2월,토요일,여성,27,서울,VIP,식품,D브랜드,10234,22248
16,Q1-00017,2026-03-01,2017,3025,1,0.00,계좌이체,모바일앱,정상,3월,일요일,남성,37,경기,VIP,식품,A브랜드,9870,25177
25,Q1-00026,2026-03-15,2142,3041,4,0.10,계좌이체,웹,정상,3월,일요일,여성,27,서울,VIP,도서,D브랜드,13298,30884
33,Q1-00034,2026-03-14,2144,3035,5,0.15,카드,오프라인,정상,3월,토요일,남성,18,서울,VIP,패션,C브랜드,42086,69807
39,Q1-00040,2026-03-03,2048,3050,2,0.10,계좌이체,웹,정상,3월,화요일,여성,55,전라,VIP,식품,B브랜드,12489,25637

In [25]:
# 총매출액, 할인액, 순매출액, 이익, 실매출액 변수 생성.

orders['총매출액'] = orders['판매가'] * orders['수량']
orders['할인액'] = orders['할인율'] * orders['판매가'] * orders['수량']   
orders['실매출액'] = orders['총매출액'] - orders['할인액']                
orders['순매출액'] = orders['실매출액']
orders['이익'] = orders['순매출액'] - orders['원가'] * orders['수량']

orders

,주문ID,주문일자,고객ID,상품ID,수량,할인율,결제수단,판매채널,환불여부,주문월,...,회원등급,카테고리,브랜드,원가,판매가,총매출액,할인액,실매출액,순매출액,이익
0,Q1-00001,2026-02-12,2057,3045,4,0.10,간편결제,모바일앱,정상,2월,...,일반,식품,C브랜드,9809,16670,66680,6668.00,60012.00,60012.00,20776.00
1,Q1-00002,2026-02-22,2054,3044,3,0.10,카드,모바일앱,정상,2월,...,일반,식품,C브랜드,10960,20808,62424,6242.40,56181.60,56181.60,23301.60
2,Q1-00003,2026-01-30,2084,3048,4,0.05,카드,모바일앱,정상,1월,...,실버,패션,D브랜드,36520,67712,270848,13542.40,257305.60,257305.60,111225.60
3,Q1-00004,2026-03-05,2091,3001,3,0.20,계좌이체,모바일앱,정상,3월,...,일반,패션,A브랜드,39896,61987,185961,37192.20,148768.80,148768.80,29080.80
4,Q1-00005,2026-02-28,2142,3027,4,0.05,계좌이체,웹,정상,2월,...,VIP,식품,D브랜드,10234,22248,88992,4449.60,84542.40,84542.40,43606.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,Q2-00506,2026-05-19,2052,3021,1,0.00,계좌이체,모바일앱,정상,5월,...,일반,도서,A브랜드,15115,31465,31465,0.00,31465.00,31465.00,16350.00
966,Q2-00507,2026-06-18,2113,3012,5,0.00,무통장,모바일앱,정상,6월,...,일반,식품,D브랜드,8598,18620,93100,0.00,93100.00,93100.00,50110.00
967,Q2-00508,2026-05-13,2135,3021,4,0.10,간편결제,웹,정상,5월,...,VIP,도서,A브랜드,15115,31465,125860,12586.00,113274.00,113274.00,52814.00
968,Q2-00509,2026-04-01,2046,3039,5,0.15,무통장,웹,정상,4월,...,실버,패션,D브랜드,45262,91357,456785,68517.75,388267.25,388267.25,161957.25
969,Q2-00510,2026-04-21,2103,3037,4,0.15,카드,모바일앱,정상,4월,...,VIP,패션,B브랜드,33376,74717,298868,44830.20,254037.80,254037.80,120533.80

총매출액, 할인액, 순매출액, 이익, 실매출액 변수를 생성하시오.
전자기기 카테고리의 고액 정상 주문을 필터링하고 정렬하시오.
카테고리별 주문건수, 판매수량, 실매출액, 실이익을 집계하시오.
회원등급을 순서형 인코딩하시오.
카테고리, 지역, 결제수단, 판매채널을 원-핫 인코딩하시오.
매출 관련 수치형 컬럼을 스케일링하시오.
최종 분석용 데이터와 모델 입력용 데이터를 CSV로 저장하시오.